services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    restart: always
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 30s
      retries: 5
    restart: always

volumes:
  mongo_data:
