name: Build And Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # 만약 커밋 메시지가 deploy 으로 시작하면 실행한다.
    if: startsWith(github.event.head_commit.message, 'deploy')
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo sh -c 'truncate -s 0 /var/lib/docker/containers/*/*-json.log'
            cd ~/${{ secrets.REPOSITORY_NAME }}
            git checkout main 
            git stash push || true
            git pull
            git stash clear || true
            sudo docker compose down && sudo docker compose up -d --build
            sudo docker image prune -af
